trigger:
  batch: true

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 2
  - pwsh: |
      Write-Host $(Build.SourcesDirectory)
      pwd
      ls
      git diff --name-only HEAD..HEAD~1
    workingDirectory: $(Build.SourcesDirectory)

  - pwsh: |
      Write-Host 'Task next to git diff'

