trigger:
  batch: true

pool:
  vmImage: ubuntu-latest

steps:
  - pwsh: |
      Write-Host $(Build.SourcesDirectory)
      ls $(Build.SourcesDirectory)
      git diff --name-only main..main~1
    workingDirectory: $(Build.SourcesDirectory)

  - pwsh: |
      Write-Host 'Task next to git diff'

