trigger:
  batch: true

pool:
  vmImage: ubuntu-latest

steps:
  - pwsh: |
      git diff --name-only HEAD HEAD~1
    workingDirectory: $(Build.SourcesDirectory)

  - pwsh: |
      Write-Host 'Task next to git diff'

      